### ISSUE TITLE
Allow file upload of files containing identifiers

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#10]
Submitted by @jtgorman to JIRA on 3/18/2019:

> Allow uploading a file containing identifiers and being able to then see or export a list of matching entries.
>
> For example, a report might be made to get a list of books from a certain country during a time range in Voyager. That yields a list of just over a thousand bib ids from a Voyager report. The person then wants to find out which of these are already contained in a digital form.
>
> Some way to quickly find which of these records have already been been processed shoudl be a matter of uploading a file.
>
> Not the current interface has a text area for adding identifiers, but it's not clear to me exactly how ones provides a list of identifiers. Neither a newline or a tab delimited list seems to work.

**Comment by gaurijo** [comment]
@adolski Is this issue talking about the text area where you search/filter by IDs? Is this issue asking for a place to upload a file of identifiers in addition to the existing filtering function?

**Comment by adolski** [comment]
Good question:

> Note the current interface has a text area for adding identifiers, but it's not clear to me exactly how ones provides a list of identifiers. Neither a newline or a tab delimited list seems to work.

I just pasted in a newline-separated list of 3 bib IDs into the textarea, and it worked. So I wonder why @jtgorman's list didn't work. Maybe the query slows down as the list size increases, and becomes too slow?

Our first resort should be to figure out what's wrong with the textarea (if anything) and fix it if possible. If it's just that the query is slow, then a file upload feature would suffer the same problem.

**Comment by jtgorman** [comment]
I honestly don't remember the initial cause for this, although I guess I could dig around if needed. It also might just be a bug that got fixed by something else, since the original is from 2019 and from back in the day when we had Voyager instead of Alma as the catalog.

Trying it with a larger size of ids isn't a terrible idea either.

**Comment by gaurijo** [comment]
I just ran it with approx. 25 ids and the query wasn't slow at all, but I don't know if that's a large enough size of ids to verify.

**Comment by jtgorman** [comment]
Honestly, I don't think I've looked at the app since I filed this, and I think I filed this on behalf of some other uesr and no clue who that was at this point. I'd lean towards just closing it.  If someone needs it, hopefully they'll just ask again

**Comment by gaurijo** [comment]
I'll dig around a bit more, but if I don't notice any problems I'll go ahead and close this issue. 

Thanks @jtgorman!

**Comment by adolski** [comment]
OK, thanks @jtgorman!
