### ISSUE TITLE
Internal server error when retrieving the book list as XML

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#29]
From an email from @srbbins:

This URL returns HTTP 500: https://book-tracker.library.illinois.edu/books.xml?ht=&ia=&in%5B%5D=ht&q=30112110879274

**Comment by gaurijo** [comment]
Adding some more context/how to produce the error locally:

- start rails server -> `bin/rails server` and go to `http://localhost:3000`
- log in with `admin credentials`
- Click on `Export` and choose `MARCXML`


![Image](https://github.com/medusa-project/book-tracker/assets/103534307/3bdba3e3-d908-4b76-ae8f-2a675bee9d06)

The following error will come up:



![Image](https://github.com/medusa-project/book-tracker/assets/103534307/5962526c-f543-453a-abf5-0b5540f50035)

And the same error comes up if you choose `CSV` 

![Image](https://github.com/medusa-project/book-tracker/assets/103534307/fc557972-4345-48a5-a9a6-38db0e478a32)
