### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by adolski** [medusa-project/book-tracker#3]
Add at least partial unit test coverage, refactoring for better testability where necessary.

**Comment by gaurijo** [comment]
Book methods w/test coverage:
- bulk_upsert
- bulk_update
- internet_archive_url 
- hathitrust_handle
- uiuc_catalog_url
- as_json
- to_csv
- params_from_marcxml

(in progress):

- service 
- user tests *

**Comment by adolski** [comment]
@gaurijo I've renamed this and opened #17 for the controller tests.
