### ISSUE TITLE
Failing TempStore and BookStore Tests

### ISSUE THREAD

**Issue by gaurijo** [medusa-project/book-tracker#35]
![Image](https://github.com/medusa-project/book-tracker/assets/103534307/d32af2b6-eb5e-4091-883d-fc2f73d7fe2b)

![Image](https://github.com/medusa-project/book-tracker/assets/103534307/3c80ff3d-7557-4280-81a8-f0e796e1d84c)

**Comment by adolski** [comment]
I'm not familiar with either of these errors, but I'd guess it's a strong possibility that the test failures are being caused by whatever is wrong with Minio.

**Comment by gaurijo** [comment]
@adolski I think you're right. I'm going to see if I can reinstall minio because I believe I originally installed it under x86_64 architecture and that might be why things are bugging out on my end.

In the mean time, if there are other book-tracker issues that I can get started on please feel free to move them to the to-do column and I'll get to them soon.

**Comment by gaurijo** [comment]
This seems to be resolved now. As expected, I needed to reinstall minio for `ARM `(`arch -arm64 brew install minio`) and restart it (`brew services restart minio`).

Tests now pass again and the error about storage no longer pops up when I access the minio url.
